//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersona
    {
        public int PKPersona { get; set; }
        public string DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public int FkLocalidad_TblLocalidad { get; set; }
        public int FkGenero_TblGenero { get; set; }
        public int FkEstadoCivil_TblEstadoCivil { get; set; }
        public int FkProvincia_TblProvincia { get; set; }
    
        public virtual TblEstadoCivil TblEstadoCivil { get; set; }
        public virtual TblGenero TblGenero { get; set; }
        public virtual TblLocalidad TblLocalidad { get; set; }
        public virtual TblProvincia TblProvincia { get; set; }
    }
}
